version: "3.7"
services:
  database:
    image: gitlab-edu.supsi.ch:5050/dacd-ist/geomatica/iststa/istsos-miu-database:0.0.1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATADIR: /var/lib/postgresql/data
    command: >
      postgres -c custom.hostname="${HOSTNAME}" -c custom.subpath="${SUBPATH}" -c custom.version="${VERSION}" -c custom.versioning="${VERSIONING}" -c log_statement="all" -c log_destination="stderr"
    ports:
      - "45432:5432"
    volumes:
      - v-istsos-miu-database-data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: gitlab-edu.supsi.ch:5050/dacd-ist/geomatica/iststa/istsos-miu-fastapi:0.0.1
    environment:
      DATABASE_URL: postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database:5432/${POSTGRES_DB}
      HOSTNAME: ${HOSTNAME}
      SUBPATH: ${SUBPATH}
      VERSION: ${VERSION}
      DEBUG: ${DEBUG}
    command: uvicorn --reload --workers 1 --host 0.0.0.0 --port 5000 app.main:app
    ports:
      - 8018:5000
    working_dir: /code

  dummy_data:
    image: gitlab-edu.supsi.ch:5050/dacd-ist/geomatica/iststa/istsos-miu-dummy-data:0.0.1
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DUMMY_DATA: ${DUMMY_DATA}
      CLEAR_DATA: ${CLEAR_DATA}
      N_THINGS: ${N_THINGS}
      N_OBSERVED_PROPERTIES: ${N_OBSERVED_PROPERTIES}
      INTERVAL: ${INTERVAL}
      FREQUENCY: ${FREQUENCY}
      START_DATETIME: ${START_DATETIME}
      CHUNK_INTERVAL: ${CHUNK_INTERVAL}
    command: python3 generator.py
    working_dir: /dummy_data
    depends_on:
      database:
        condition: service_healthy

volumes:
  v-istsos-miu-database-data:
    name: v-istsos-miu-database-data
