version: "3.7"
services:

  database:
    image: gitlab-edu.supsi.ch:5050/dacd-ist/geomatica/iststa/istsos-miu-database:0.0.5
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DATADIR: /var/lib/postgresql/data
    command: >
      postgres -c custom.versioning="${VERSIONING}" -c custom.duplicates="${DUPLICATES}" -c custom.epsg="${EPSG}" -c log_statement="all" -c log_destination="stderr" -c log_duration="on"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: gitlab-edu.supsi.ch:5050/dacd-ist/geomatica/iststa/istsos-miu-fastapi:0.0.12
    environment:
      HOSTNAME: ${HOSTNAME}
      SUBPATH: ${SUBPATH}
      VERSION: ${VERSION}
      DEBUG: ${DEBUG}
      VERSIONING: ${VERSIONING}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PG_MAX_OVERFLOW: ${PG_MAX_OVERFLOW}
      PG_POOL_SIZE: ${PG_POOL_SIZE}
      PG_POOL_TIMEOUT: ${PG_POOL_TIMEOUT}
      COUNT_MODE: ${COUNT_MODE}
      COUNT_ESTIMATE_THRESHOLD: ${COUNT_ESTIMATE_THRESHOLD}
      TOP_VALUE: ${TOP_VALUE}
      PARTITION_CHUNK: ${PARTITION_CHUNK}
      REDIS: ${REDIS}
      EPSG: ${EPSG}
    command: uvicorn --timeout-keep-alive 75 --workers 2 --host 0.0.0.0 --port 5000 app.main:app
    ports:
      - 8000:5000
    working_dir: /code

  redis:
    image: redis:7.4.0-alpine3.20
    restart: always
