site_name: istSOS4
site_author: "istSOS4 Things"
site_url: https://ord.supsi.ch/

repo_name: "GitLab"
repo_url: "https://gitlab.com/geo-ord/osires_code"
docs_dir: "docs"
theme:
  name: "material"
  language: en
  favicon: assets/images/favicon.ico
  logo: assets/images/istsos_bars_white.png
  font:
    text: Ubuntu
  palette:
    scheme: istsos
    # - media: "(prefers-color-scheme: light)"
    #   scheme: default
    #   toggle:
    #     icon: material/toggle-switch-off-outline
    #     name: Switch to dark mode
    # - media: "(prefers-color-scheme: dark)"
    #   scheme: slate
    #   toggle:
    #     icon: material/toggle-switch
    #     name: Switch to light mode
  extra_css:
    - extra.css
  features:
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - navigation.top

nav:
  # SET HERE THE CONTENT PAGES IN THE APPROPRIATE CHAPTER
  # =====================================================
  - The Project:
      - Introduction: populate_basic.ipynb
      - Introduction: project/introduction.md
      - History: project/history.md
      - Resources: project/resources.md
  - User Documentation:
      - Installation: userdocs/installation.md
      - Configuration: userdocs/configuration.md
      - User Guide: userdocs/userguide.md
      - FAQ: userdocs/faq.md
  - Developer Documentation:
      - Installation: devdocs/installation.md
      - Configuration: devdocs/configuration.md
      - API: devdocs/api.md
      - Extensions: devdocs/extensions.md
  - Tutorial:
      - tutorial/tutorial_index.md
      - Manage Authentication & Authorization:
          - Concepts and Theory: tutorial/authorization.md
          - Hands-On Example (Python): tutorial/authorization_notebook.ipynb
      # - Introduction: tutorial/introduction.md
      # - Tutorial: tutorial/tutorial.md
  - Team: team.md

extra_css:
  - assets/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.magiclink
  - pymdownx.highlight
  - pymdownx.tabbed
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - mkdocs-video
  - mknotebooks
  - bibtex:
      bib_file: "./docs/refs.bib"
  # - git-revision-date-localized
