# config.yml content
version: 2.1


start_datetime: 2020-01-01T12:00:00.000+01:00
timestep: PT10M

static_datastreams: 
  observedProperties: 10
  quantity: 10
  observations_each: 1000

dynamic_datastreams: 
  observedProperties: 10
  quantity: 8
  observations_each: 500 